apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cocktail-api.fullname" . }}
  labels:
    {{- include "cocktail-api.labels" . | nindent 4 }}
type: Opaque
data:
  APP_KEY: {{ .Values.secrets.appKey }}
  DB_USER: {{ .Values.secrets.postgresql.username }}
  DB_PASSWORD: {{ .Values.secrets.postgresql.password }}
